separate rehash query for each partition
dataloom/mechanic pull request #78
Opened 2020-02-27 19:56 UTC by katherinebernstein

2020-02-27 20:02 UTC, you-leee approved these changes

2020-02-27 20:04 UTC, makosblade approved these changes

2020-02-28 00:37 UTC, geekbeast requested changes

2020-02-28 00:37 UTC, geekbeast commented on src/main/kotlin/com/openlattice/mechanic/upgrades/UpdateDateTimePropertyHash.kt
> -                "ON CONFLICT ($keyCols) DO UPDATE SET " +
It looks like DO UPDATE SET is missing.

2020-02-28 00:37 UTC, geekbeast commented on src/main/kotlin/com/openlattice/mechanic/upgrades/UpdateDateTimePropertyHash.kt
> +        return "WITH $cteName AS ( SELECT * FROM $TEMP_TABLE_NAME ) " +
Don't use a CTE for delete as this breaks pushdown.

2020-02-28 00:39 UTC, geekbeast commented on src/main/kotlin/com/openlattice/mechanic/upgrades/UpdateDateTimePropertyHash.kt
> +        return "WITH $cteName AS ( SELECT * FROM $TEMP_TABLE_NAME ) " +
```DELETE FROM ${DATA.name} USING $TEMP_TABLE_NAME where $colsToMatch AND ANY( $TEMP_TABLE_NAME.${OLD_HASH_COL.name})``` should do it right?

2020-02-28 00:44 UTC, katherinebernstein commented on src/main/kotlin/com/openlattice/mechanic/upgrades/UpdateDateTimePropertyHash.kt
> -                "ON CONFLICT ($keyCols) DO UPDATE SET " +
no, it's in onConflict

2020-02-28 00:50 UTC, geekbeast approved these changes

2020-02-28 00:50 UTC, merged